package uk.co.coales.data;

// Generated 06-Dec-2015 19:35:43 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Entry generated by hbm2java
 */
public class Entry implements java.io.Serializable {

	private int entryId;
	private Account account;
	private Date entryDate;
	private String entryText;
	private Set entryTags = new HashSet(0);

	public Entry() {
	}

	public Entry(int entryId, Account account, Date entryDate, String entryText) {
		this.entryId = entryId;
		this.account = account;
		this.entryDate = entryDate;
		this.entryText = entryText;
	}

	public Entry(int entryId, Account account, Date entryDate,
			String entryText, Set entryTags) {
		this.entryId = entryId;
		this.account = account;
		this.entryDate = entryDate;
		this.entryText = entryText;
		this.entryTags = entryTags;
	}

	public int getEntryId() {
		return this.entryId;
	}

	public void setEntryId(int entryId) {
		this.entryId = entryId;
	}

	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	public Date getEntryDate() {
		return this.entryDate;
	}

	public void setEntryDate(Date entryDate) {
		this.entryDate = entryDate;
	}

	public String getEntryText() {
		return this.entryText;
	}

	public void setEntryText(String entryText) {
		this.entryText = entryText;
	}

	public Set getEntryTags() {
		return this.entryTags;
	}

	public void setEntryTags(Set entryTags) {
		this.entryTags = entryTags;
	}

}
