package uk.co.coales.data;

// Generated 06-Dec-2015 19:35:43 by Hibernate Tools 4.0.0

/**
 * EntryTag generated by hbm2java
 */
public class EntryTag implements java.io.Serializable {

	private int entryTagId;
	private Entry entry;
	private String tag;

	public EntryTag() {
	}

	public EntryTag(int entryTagId, Entry entry, String tag) {
		this.entryTagId = entryTagId;
		this.entry = entry;
		this.tag = tag;
	}

	public int getEntryTagId() {
		return this.entryTagId;
	}

	public void setEntryTagId(int entryTagId) {
		this.entryTagId = entryTagId;
	}

	public Entry getEntry() {
		return this.entry;
	}

	public void setEntry(Entry entry) {
		this.entry = entry;
	}

	public String getTag() {
		return this.tag;
	}

	public void setTag(String tag) {
		this.tag = tag;
	}

}
