package uk.co.coales.data;

// Generated 06-Dec-2015 19:35:43 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * List generated by hbm2java
 */
public class List implements java.io.Serializable {

	private int listId;
	private Account account;
	private String title;
	private String description;
	private Set listItems = new HashSet(0);

	public List() {
	}

	public List(int listId, Account account, String title, String description) {
		this.listId = listId;
		this.account = account;
		this.title = title;
		this.description = description;
	}

	public List(int listId, Account account, String title, String description,
			Set listItems) {
		this.listId = listId;
		this.account = account;
		this.title = title;
		this.description = description;
		this.listItems = listItems;
	}

	public int getListId() {
		return this.listId;
	}

	public void setListId(int listId) {
		this.listId = listId;
	}

	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set getListItems() {
		return this.listItems;
	}

	public void setListItems(Set listItems) {
		this.listItems = listItems;
	}

}
