package uk.co.coales.data;

// Generated 06-Dec-2015 19:35:43 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * ListItem generated by hbm2java
 */
public class ListItem implements java.io.Serializable {

	private int listItemId;
	private List list;
	private String name;
	private String description;
	private Date dateAdded;

	public ListItem() {
	}

	public ListItem(int listItemId, List list, String name, String description,
			Date dateAdded) {
		this.listItemId = listItemId;
		this.list = list;
		this.name = name;
		this.description = description;
		this.dateAdded = dateAdded;
	}

	public int getListItemId() {
		return this.listItemId;
	}

	public void setListItemId(int listItemId) {
		this.listItemId = listItemId;
	}

	public List getList() {
		return this.list;
	}

	public void setList(List list) {
		this.list = list;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Date getDateAdded() {
		return this.dateAdded;
	}

	public void setDateAdded(Date dateAdded) {
		this.dateAdded = dateAdded;
	}

}
