package uk.co.coales.data;

// Generated 06-Dec-2015 19:35:43 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * NoteCategory generated by hbm2java
 */
public class NoteCategory implements java.io.Serializable {

	private int noteCategoryId;
	private Account account;
	private NoteCategory noteCategory;
	private String name;
	private Set notes = new HashSet(0);
	private Set noteCategories = new HashSet(0);

	public NoteCategory() {
	}

	public NoteCategory(int noteCategoryId, Account account, String name) {
		this.noteCategoryId = noteCategoryId;
		this.account = account;
		this.name = name;
	}

	public NoteCategory(int noteCategoryId, Account account,
			NoteCategory noteCategory, String name, Set notes,
			Set noteCategories) {
		this.noteCategoryId = noteCategoryId;
		this.account = account;
		this.noteCategory = noteCategory;
		this.name = name;
		this.notes = notes;
		this.noteCategories = noteCategories;
	}

	public int getNoteCategoryId() {
		return this.noteCategoryId;
	}

	public void setNoteCategoryId(int noteCategoryId) {
		this.noteCategoryId = noteCategoryId;
	}

	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	public NoteCategory getNoteCategory() {
		return this.noteCategory;
	}

	public void setNoteCategory(NoteCategory noteCategory) {
		this.noteCategory = noteCategory;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set getNotes() {
		return this.notes;
	}

	public void setNotes(Set notes) {
		this.notes = notes;
	}

	public Set getNoteCategories() {
		return this.noteCategories;
	}

	public void setNoteCategories(Set noteCategories) {
		this.noteCategories = noteCategories;
	}

}
