package uk.co.coales.data;

// Generated 06-Dec-2015 19:35:43 by Hibernate Tools 4.0.0

import java.io.Serializable;
import java.util.Date;

/**
 * RoutineItemStatus generated by hbm2java
 */
public class RoutineItemStatus implements java.io.Serializable {

	private RoutineItemStatusId id;
	private RoutineItem routineItem;
	private RoutineRun routineRun;
	private Date timeStarted;
	private Serializable duration;
	private String notes;

	public RoutineItemStatus() {
	}

	public RoutineItemStatus(RoutineItemStatusId id, RoutineItem routineItem,
			RoutineRun routineRun) {
		this.id = id;
		this.routineItem = routineItem;
		this.routineRun = routineRun;
	}

	public RoutineItemStatus(RoutineItemStatusId id, RoutineItem routineItem,
			RoutineRun routineRun, Date timeStarted, Serializable duration,
			String notes) {
		this.id = id;
		this.routineItem = routineItem;
		this.routineRun = routineRun;
		this.timeStarted = timeStarted;
		this.duration = duration;
		this.notes = notes;
	}

	public RoutineItemStatusId getId() {
		return this.id;
	}

	public void setId(RoutineItemStatusId id) {
		this.id = id;
	}

	public RoutineItem getRoutineItem() {
		return this.routineItem;
	}

	public void setRoutineItem(RoutineItem routineItem) {
		this.routineItem = routineItem;
	}

	public RoutineRun getRoutineRun() {
		return this.routineRun;
	}

	public void setRoutineRun(RoutineRun routineRun) {
		this.routineRun = routineRun;
	}

	public Date getTimeStarted() {
		return this.timeStarted;
	}

	public void setTimeStarted(Date timeStarted) {
		this.timeStarted = timeStarted;
	}

	public Serializable getDuration() {
		return this.duration;
	}

	public void setDuration(Serializable duration) {
		this.duration = duration;
	}

	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

}
