package uk.co.coales.data;

// Generated 06-Dec-2015 19:35:43 by Hibernate Tools 4.0.0

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * RoutineRun generated by hbm2java
 */
public class RoutineRun implements java.io.Serializable {

	private int routineRunId;
	private Routine routine;
	private Date timeStarted;
	private Serializable duration;
	private Set routineItemStatuses = new HashSet(0);

	public RoutineRun() {
	}

	public RoutineRun(int routineRunId, Routine routine, Date timeStarted) {
		this.routineRunId = routineRunId;
		this.routine = routine;
		this.timeStarted = timeStarted;
	}

	public RoutineRun(int routineRunId, Routine routine, Date timeStarted,
			Serializable duration, Set routineItemStatuses) {
		this.routineRunId = routineRunId;
		this.routine = routine;
		this.timeStarted = timeStarted;
		this.duration = duration;
		this.routineItemStatuses = routineItemStatuses;
	}

	public int getRoutineRunId() {
		return this.routineRunId;
	}

	public void setRoutineRunId(int routineRunId) {
		this.routineRunId = routineRunId;
	}

	public Routine getRoutine() {
		return this.routine;
	}

	public void setRoutine(Routine routine) {
		this.routine = routine;
	}

	public Date getTimeStarted() {
		return this.timeStarted;
	}

	public void setTimeStarted(Date timeStarted) {
		this.timeStarted = timeStarted;
	}

	public Serializable getDuration() {
		return this.duration;
	}

	public void setDuration(Serializable duration) {
		this.duration = duration;
	}

	public Set getRoutineItemStatuses() {
		return this.routineItemStatuses;
	}

	public void setRoutineItemStatuses(Set routineItemStatuses) {
		this.routineItemStatuses = routineItemStatuses;
	}

}
