package uk.co.coales.data;

// Generated 06-Dec-2015 19:35:43 by Hibernate Tools 4.0.0

/**
 * RoutineItemStatusId generated by hbm2java
 */
public class RoutineItemStatusId implements java.io.Serializable {

	private int routineRunId;
	private int routineItemId;

	public RoutineItemStatusId() {
	}

	public RoutineItemStatusId(int routineRunId, int routineItemId) {
		this.routineRunId = routineRunId;
		this.routineItemId = routineItemId;
	}

	public int getRoutineRunId() {
		return this.routineRunId;
	}

	public void setRoutineRunId(int routineRunId) {
		this.routineRunId = routineRunId;
	}

	public int getRoutineItemId() {
		return this.routineItemId;
	}

	public void setRoutineItemId(int routineItemId) {
		this.routineItemId = routineItemId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RoutineItemStatusId))
			return false;
		RoutineItemStatusId castOther = (RoutineItemStatusId) other;

		return (this.getRoutineRunId() == castOther.getRoutineRunId())
				&& (this.getRoutineItemId() == castOther.getRoutineItemId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getRoutineRunId();
		result = 37 * result + this.getRoutineItemId();
		return result;
	}

}
