package uk.co.coales.data;

// Generated 06-Dec-2015 19:35:43 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * RoutineItem generated by hbm2java
 */
public class RoutineItem implements java.io.Serializable {

	private int routineItemId;
	private Routine routine;
	private String name;
	private String description;
	private boolean optional;
	private boolean timed;
	private Set routineItemStatuses = new HashSet(0);

	public RoutineItem() {
	}

	public RoutineItem(int routineItemId, Routine routine, String name,
			String description, boolean optional, boolean timed) {
		this.routineItemId = routineItemId;
		this.routine = routine;
		this.name = name;
		this.description = description;
		this.optional = optional;
		this.timed = timed;
	}

	public RoutineItem(int routineItemId, Routine routine, String name,
			String description, boolean optional, boolean timed,
			Set routineItemStatuses) {
		this.routineItemId = routineItemId;
		this.routine = routine;
		this.name = name;
		this.description = description;
		this.optional = optional;
		this.timed = timed;
		this.routineItemStatuses = routineItemStatuses;
	}

	public int getRoutineItemId() {
		return this.routineItemId;
	}

	public void setRoutineItemId(int routineItemId) {
		this.routineItemId = routineItemId;
	}

	public Routine getRoutine() {
		return this.routine;
	}

	public void setRoutine(Routine routine) {
		this.routine = routine;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public boolean isOptional() {
		return this.optional;
	}

	public void setOptional(boolean optional) {
		this.optional = optional;
	}

	public boolean isTimed() {
		return this.timed;
	}

	public void setTimed(boolean timed) {
		this.timed = timed;
	}

	public Set getRoutineItemStatuses() {
		return this.routineItemStatuses;
	}

	public void setRoutineItemStatuses(Set routineItemStatuses) {
		this.routineItemStatuses = routineItemStatuses;
	}

}
